### ISSUE TITLE
rtk-cl-utils dependency

### ISSUE THREAD

**Issue by Frechmatz** [RyanTKing/cl-wave#1]
Hi Ryan,
i'm wondering about the rtk-cl-utils dependency of your cl-wave library. I cannot find any repository that implements this dependency. I've removed the dependency in my fork, but get compilation errors about undefined functions such as let1 and sint. Nevertheless when ignoring these errors your library works fine, at least for writing Wave files.
Best regards,
Oliver

**Comment by ryantking** [comment]
Hi Oliver,
`rtk-cl-utils` is just my personal repository of macros and such that I got tired of rewriting in every CL. `let1` is just a `let` statement without the double parenthesis nastiness:
```lisp
(defmacro let1 ((var val) &body body)
  `(let ((,var ,val))
     ,@body))
```
I believe `sint` is just a variable name I use to differentiate between signed ints and unsigned ints.

Best regards,
Ryan

**Comment by Frechmatz** [comment]
Hi Ryan, thanks for your answer. As this is kind of critical code were changes needs to be thoroughly tested, i would like to ask you, if you could add your macros to the project?
Thanks and regards,
Oliver

**Comment by ryantking** [comment]
Definitely, I should also set this project up with Travis and some tests. I'll do all that this evening.

**Comment by ryantking** [comment]
PR is merged, thanks!
